version: '3'

services:
  rancher-master:
    container_name: rancher-server
    image: ubuntu
    hostname:
        rancher-server  
    volumes:
      - rancher-master:/data/rancher
    networks:
      - rancher

  rancher-node1:
    container_name: rancher-node1
    image: ubuntu
    hostname:
        rancher-node1
    volumes:
      - rancher-node1:/data/rancher
    networks:
      - rancher

  rancher-node2:
    container_name: rancher-node2
    image: ubuntu
    hostname:
        rancher-node2 
    volumes:
      - rancher-node2:/var/opt/mssql/data/sqlNode3
    networks:
      - rancher

volumes:
  rancher-server:
  rancher-node1:
  rancher-node2:
  
networks:
  rancher:
